---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
data:
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  CART_HOST: "cart"
  CART_PORT: "8080"
  SHIPPING_HOST: "shipping"
  SHIPPING_PORT: "8080"
  PAYMENT_HOST: "payment"
  PAYMENT_PORT: "8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb-dev.chanakyakolli.online:27017/catalogue"
  DB_TYPE: "mongo"
  APP_GIT_URL: "https://github.com/roboshop-devops-project-v3/catalogue"
  DB_HOST: "mongodb-dev.chanakyakolli.online"
  SCHEMA_FILE: "db/master-data.js"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb-dev.chanakyakolli.online:27017/users"
  REDIS_URL: "redis://redis-dev.chanakyakolli.online:6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
data:
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
  REDIS_HOST: "redis-dev.chanakyakolli.online"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql-dev.chanakyakolli.online"
  DB_TYPE: "mysql"
  APP_GIT_URL: "https://github.com/roboshop-devops-project-v3/shipping"
  DB_USER: "root"
  DB_PASS: "RoboShop@1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq-dev.chanakyakolli.online"
  AMQP_USER: "roboshop"
  AMQP_PASS: "roboshop123"
---
apiVersion: v1
kind: Service
metadata:
  name: Frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
    project: robot-shop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    app: catalogue
    project: robot-shop
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    app: cart
    project: robot-shop
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    app: user
    project: robot-shop
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  selector:
    app: shipping
    project: robot-shop
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    app: payment
    project: robot-shop
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
    project: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      project: robot-shop
  template:
    metadata:
      labels:
        app: frontend
        project: robot-shop
    spec:
      containers:
        - name: frontend
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
          envFrom:
            - configMapRef:
                name: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: catalogue
    project: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
      project: robot-shop
  template:
    metadata:
      labels:
        app: catalogue
        project: robot-shop
    spec:
      containers:
        - name: catalogue
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/catalogue
          envFrom:
            - configMapRef:
                name: catalogue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cart
    project: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
      project: robot-shop
  template:
    metadata:
      labels:
        app: cart
        project: robot-shop
    spec:
      containers:
        - name: cart
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/cart
          envFrom:
            - configMapRef:
                name: cart
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user
    project: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
      project: robot-shop
  template:
    metadata:
      labels:
        app: user
        project: robot-shop
    spec:
      containers:
        - name: user
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/user
          envFrom:
            - configMapRef:
                name: user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shipping
    project: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
      project: robot-shop
  template:
    metadata:
      labels:
        app: shipping
        project: robot-shop
    spec:
      containers:
        - name: shipping
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/shipping
          envFrom:
            - configMapRef:
                name: shipping
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment
    project: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
      project: robot-shop
  template:
    metadata:
      labels:
        app: payment
        project: robot-shop
    spec:
      containers:
        - name: payment
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/payment
          envFrom:
            - configMapRef:
                name: payment
---
apiVersion: batch/v1
kind: Job
metadata:
  name: catalogue-schema
spec:
  template:
    metadata:
      labels:
        app: catalogue
        project: robot-shop
    spec:
      restartPolicy: Never
      containers:
        - name: catalogue-schema
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
          envFrom:
            - configMapRef:
                name: catalogue
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: shipping-schema-user
spec:
  template:
    metadata:
      labels:
        app: shipping
        project: robot-shop
    spec:
      restartPolicy: Never
      containers:
        - name: shipping-schema
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
          env:
            - name: SCHEMA_FILE
              value: "db/app-user.sql"
          envFrom:
            - configMapRef:
                name: shipping
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: shipping-schema
spec:
  template:
    metadata:
      labels:
        app: shipping
        project: robot-shop
    spec:
      restartPolicy: Never
      containers:
        - name: shipping-schema
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
          env:
            - name: SCHEMA_FILE
              value: "db/schema.sql"
          envFrom:
            - configMapRef:
                name: shipping
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: shipping-schema-data
spec:
  template:
    metadata:
      labels:
        app: shipping
        project: robot-shop
    spec:
      restartPolicy: Never
      containers:
        - name: shipping-schema
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
          env:
            - name: SCHEMA_FILE
              value: "db/master-data.sql"
          envFrom:
            - configMapRef:
                name: shipping
  backoffLimit: 0
---
