---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: frontend
spec:
  containers:
    - name: service-demo
      image: nginx
      ports:
        - containerPort: 80

--- ## ClusterIP (default):
## Provides an internal virtual IP that load balances traffic to Pods across the cluster.
## Accessible only within the cluster.
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: service-demo
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

--- ## NodePort:
## Exposes the Service on a static port on every node.
## External clients can access via <NodeIP>:NodePort if network allows.

apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: service-demo-np
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
--- ## LoadBalancer:
## Provisions an external load balancer (cloud environments).
## Exposes the Service publicly and routes traffic to Pods.
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: service-demo-lb
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
